# Generated by Django 5.2.4 on 2025-07-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_brand_alter_car_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='teste',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
