# Generated by Django 5.2.4 on 2025-07-31 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='teste',
        ),
    ]
