# Generated by Django 5.2.4 on 2025-08-26 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_inventory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car_Inventory',
            new_name='CarInventory',
        ),
    ]
