# Generated by Django 5.2.4 on 2025-08-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_rename_car_inventory_carinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
